"""Type stubs for lifxlan package."""

from typing import List, Optional, Tuple

# Color constants
RED: Tuple[int, int, int, int]
ORANGE: Tuple[int, int, int, int]
YELLOW: Tuple[int, int, int, int]
GREEN: Tuple[int, int, int, int]
CYAN: Tuple[int, int, int, int]
BLUE: Tuple[int, int, int, int]
PURPLE: Tuple[int, int, int, int]
PINK: Tuple[int, int, int, int]
WHITE: Tuple[int, int, int, int]

class Device:
    """Base class for LIFX devices."""

    def get_label(self) -> str: ...
    def set_label(self, label: str) -> None: ...
    def get_power(self) -> str: ...
    def set_power(self, power: str, duration: int = ..., rapid: bool = ...) -> None: ...
    def get_color(self) -> Tuple[int, int, int, int]: ...
    def set_color(
        self,
        color: Tuple[int, int, int, int],
        duration: int = ...,
        rapid: bool = ...
    ) -> None: ...

class Light(Device):
    """Represents a LIFX light device."""

    def get_brightness(self) -> int: ...
    def set_brightness(
        self,
        brightness: int,
        duration: int = ...,
        rapid: bool = ...
    ) -> None: ...
    def get_kelvin(self) -> int: ...
    def set_kelvin(
        self,
        kelvin: int,
        duration: int = ...,
        rapid: bool = ...
    ) -> None: ...

class LifxLAN:
    """Main class for controlling LIFX devices on a LAN."""

    def __init__(self, num_lights: Optional[int] = ...) -> None: ...
    def get_lights(self) -> Optional[List[Device]]: ...
    def get_color_lights(self) -> Optional[List[Light]]: ...
    def get_brightness_lights(self) -> Optional[List[Light]]: ...
    def set_power_all(
        self,
        power: str,
        duration: int = ...,
        rapid: bool = ...
    ) -> None: ...
    def set_color_all(
        self,
        color: Tuple[int, int, int, int],
        duration: int = ...,
        rapid: bool = ...
    ) -> None: ...
